# Generated by Django 4.1.7 on 2023-03-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=255)),
                ('display_format', models.CharField(choices=[('3D', '3D'), ('2D', '2D')], default='2D', max_length=2)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='poster/')),
                ('age_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_link', models.URLField(blank=True, null=True)),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('title', 'director', 'rent_start_date', 'rent_end_date')},
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='cinema_hall.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='screening.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_sold', models.BooleanField(default=False)),
                ('session_date_time', models.DateTimeField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screening.screeningsession')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema_hall.seat')),
            ],
            options={
                'unique_together': {('screening', 'seat', 'session_date_time')},
            },
        ),
    ]
