# Generated by Django 4.1.7 on 2023-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_delete_raw"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatsPriceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name="seats",
            name="x_graph",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="seats",
            name="y_graph",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
